IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'myDB')
  BEGIN
    CREATE DATABASE [myDB]
    END
    GO
       USE [myDB]
    GO
--You need to check if the table exists

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='user_roles' and xtype='U')
BEGIN
    CREATE TABLE user_roles(
		id INT NOT NULL CONSTRAINT user_roles_pk PRIMARY KEY NONCLUSTERED, 
		role_name VARCHAR(64) NOT NULL
	);
	INSERT INTO user_roles VALUES (0, 'Website Admin'), (1, 'Study Admin'), (2, 'User');
END

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='users' and xtype='U')
BEGIN
    CREATE TABLE users(
		id VARCHAR(36) NOT NULL CONSTRAINT user_pk PRIMARY KEY NONCLUSTERED, 
		linkblue VARCHAR(36) NOT NULL, 
		role INT DEFAULT 2 NOT NULL, 
		p_hash VARCHAR(255),
		phone_number VARCHAR(20),
		CONSTRAINT user_role_id_fk FOREIGN KEY (role) REFERENCES user_roles (id) ON DELETE CASCADE ON UPDATE CASCADE)
END

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='user_sessions' and xtype='U')
BEGIN
    CREATE TABLE user_sessions(session_id VARCHAR(36) NOT NULL CONSTRAINT user_sessions_pk PRIMARY KEY NONCLUSTERED, user_id VARCHAR(36) NOT NULL CONSTRAINT user_sessions_users_id_fk REFERENCES users ON DELETE CASCADE, last_seen   DATETIME DEFAULT getdate() NOT NULL, remember_me BIT DEFAULT 0 NOT NULL)
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID('users') AND name='user_linkblue_uindex')
BEGIN
    CREATE UNIQUE INDEX user_linkblue_uindex ON users (linkblue)
END

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='protocol_types' and xtype='U')
BEGIN
    CREATE TABLE protocol_types(
		protocol_type_uuid UNIQUEIDENTIFIER NOT NULL CONSTRAINT protocol_type_pk PRIMARY KEY NONCLUSTERED, 
		name VARCHAR(255) NOT NULL UNIQUE);
END

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='participants' and xtype='U')
BEGIN
    CREATE TABLE participants(
		participant_uuid UNIQUEIDENTIFIER NOT NULL CONSTRAINT participant_pk PRIMARY KEY NONCLUSTERED, 
		participant_json NVARCHAR(MAX) NOT NULL);
END

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='enrollments' and xtype='U')
BEGIN
    CREATE TABLE enrollments(
		enrollment_uuid UNIQUEIDENTIFIER NOT NULL CONSTRAINT enrollment_pk PRIMARY KEY NONCLUSTERED,
		participant_uuid UNIQUEIDENTIFIER NOT NULL CONSTRAINT participant_fk REFERENCES participants(participant_uuid) ON UPDATE CASCADE ON DELETE CASCADE, 
		protocol_type_uuid UNIQUEIDENTIFIER NOT NULL CONSTRAINT protocol_type_fk REFERENCES protocol_types(protocol_type_uuid) ON UPDATE CASCADE ON DELETE CASCADE);
END

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='messages' and xtype='U')
BEGIN
    CREATE TABLE messages(
		message_uuid UNIQUEIDENTIFIER NOT NULL CONSTRAINT message_pk PRIMARY KEY NONCLUSTERED,
		participant_uuid UNIQUEIDENTIFIER NOT NULL CONSTRAINT participant_message_fk REFERENCES participants(participant_uuid) ON UPDATE CASCADE ON DELETE CASCADE, 
		TS DATETIME NOT NULL,
		message_direction CHAR(8) NOT NULL, /* incoming or outgoing */
		message_json NVARCHAR(MAX) NOT NULL);
END

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='save_state' and xtype='U')
BEGIN
    CREATE TABLE save_state(
		enrollment_uuid UNIQUEIDENTIFIER NOT NULL CONSTRAINT state_enrollment_fk REFERENCES enrollments(enrollment_uuid) ON UPDATE CASCADE ON DELETE CASCADE,
		TS DATETIME NOT NULL,
		state_json NVARCHAR(MAX) NOT NULL);
END

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='state_log' and xtype='U')
BEGIN
    CREATE TABLE state_log(
		participant_uuid UNIQUEIDENTIFIER NOT NULL,
		TS DATETIME NOT NULL,
		log_json NVARCHAR(MAX) NOT NULL);
END

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='surveys' and xtype='U')
BEGIN
    CREATE TABLE surveys(
		token UNIQUEIDENTIFIER NOT NULL,
		participant_uuid UNIQUEIDENTIFIER NOT NULL,
		created_at DATETIME NOT NULL,
		finished_at DATETIME,
		survey_json NVARCHAR(MAX));
END

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='time_zones' and xtype='U')
BEGIN
	CREATE TABLE [dbo].[time_zones](
	[time_zone] [varchar](64) NOT NULL,
	[short_zone] [varchar](32) NOT NULL)

	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Abidjan', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Accra', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Addis_Ababa', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Algiers', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Asmara', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Asmera', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Bamako', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Bangui', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Banjul', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Bissau', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Blantyre', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Brazzaville', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Bujumbura', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Cairo', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Casablanca', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Ceuta', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Conakry', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Dakar', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Dar_es_Salaam', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Djibouti', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Douala', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/El_Aaiun', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Freetown', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Gaborone', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Harare', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Johannesburg', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Juba', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Kampala', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Khartoum', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Kigali', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Kinshasa', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Lagos', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Libreville', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Lome', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Luanda', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Lubumbashi', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Lusaka', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Malabo', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Maputo', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Maseru', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Mbabane', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Mogadishu', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Monrovia', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Nairobi', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Ndjamena', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Niamey', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Nouakchott', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Ouagadougou', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Porto-Novo', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Sao_Tome', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Timbuktu', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Tripoli', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Tunis', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Africa/Windhoek', N'Africa')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Adak', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Anchorage', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Anguilla', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Antigua', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Araguaina', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Argentina/Buenos_Aires', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Argentina/Catamarca', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Argentina/ComodRivadavia', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Argentina/Cordoba', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Argentina/Jujuy', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Argentina/La_Rioja', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Argentina/Mendoza', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Argentina/Rio_Gallegos', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Argentina/Salta', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Argentina/San_Juan', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Argentina/San_Luis', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Argentina/Tucuman', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Argentina/Ushuaia', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Aruba', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Asuncion', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Atikokan', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Atka', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Bahia', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Bahia_Banderas', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Barbados', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Belem', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Belize', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Blanc-Sablon', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Boa_Vista', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Bogota', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Boise', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Buenos_Aires', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Cambridge_Bay', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Campo_Grande', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Cancun', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Caracas', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Catamarca', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Cayenne', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Cayman', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Chicago', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Chihuahua', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Coral_Harbour', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Cordoba', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Costa_Rica', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Creston', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Cuiaba', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Curacao', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Danmarkshavn', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Dawson', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Dawson_Creek', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Denver', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Detroit', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Dominica', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Edmonton', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Eirunepe', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/El_Salvador', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Ensenada', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Fort_Nelson', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Fort_Wayne', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Fortaleza', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Glace_Bay', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Godthab', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Goose_Bay', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Grand_Turk', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Grenada', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Guadeloupe', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Guatemala', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Guayaquil', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Guyana', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Halifax', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Havana', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Hermosillo', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Indiana/Indianapolis', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Indiana/Knox', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Indiana/Marengo', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Indiana/Petersburg', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Indiana/Tell_City', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Indiana/Vevay', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Indiana/Vincennes', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Indiana/Winamac', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Indianapolis', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Inuvik', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Iqaluit', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Jamaica', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Jujuy', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Juneau', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Kentucky/Louisville', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Kentucky/Monticello', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Knox_IN', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Kralendijk', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/La_Paz', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Lima', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Los_Angeles', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Louisville', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Lower_Princes', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Maceio', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Managua', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Manaus', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Marigot', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Martinique', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Matamoros', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Mazatlan', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Mendoza', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Menominee', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Merida', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Metlakatla', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Mexico_City', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Miquelon', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Moncton', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Monterrey', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Montevideo', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Montreal', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Montserrat', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Nassau', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/New_York', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Nipigon', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Nome', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Noronha', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/North_Dakota/Beulah', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/North_Dakota/Center', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/North_Dakota/New_Salem', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Ojinaga', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Panama', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Pangnirtung', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Paramaribo', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Phoenix', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Port-au-Prince', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Port_of_Spain', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Porto_Acre', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Porto_Velho', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Puerto_Rico', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Punta_Arenas', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Rainy_River', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Rankin_Inlet', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Recife', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Regina', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Resolute', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Rio_Branco', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Rosario', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Santa_Isabel', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Santarem', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Santiago', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Santo_Domingo', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Sao_Paulo', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Scoresbysund', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Shiprock', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Sitka', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/St_Barthelemy', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/St_Johns', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/St_Kitts', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/St_Lucia', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/St_Thomas', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/St_Vincent', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Swift_Current', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Tegucigalpa', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Thule', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Thunder_Bay', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Tijuana', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Toronto', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Tortola', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Vancouver', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Virgin', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Whitehorse', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Winnipeg', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Yakutat', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'America/Yellowknife', N'America')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Antarctica/Casey', N'Antarctica')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Antarctica/Davis', N'Antarctica')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Antarctica/DumontDUrville', N'Antarctica')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Antarctica/Macquarie', N'Antarctica')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Antarctica/Mawson', N'Antarctica')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Antarctica/McMurdo', N'Antarctica')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Antarctica/Palmer', N'Antarctica')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Antarctica/Rothera', N'Antarctica')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Antarctica/South_Pole', N'Antarctica')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Antarctica/Syowa', N'Antarctica')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Antarctica/Troll', N'Antarctica')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Antarctica/Vostok', N'Antarctica')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Arctic/Longyearbyen', N'Arctic')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Aden', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Almaty', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Amman', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Anadyr', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Aqtau', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Aqtobe', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Ashgabat', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Ashkhabad', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Atyrau', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Baghdad', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Bahrain', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Baku', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Bangkok', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Barnaul', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Beirut', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Bishkek', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Brunei', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Calcutta', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Chita', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Choibalsan', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Chongqing', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Chungking', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Colombo', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Dacca', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Damascus', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Dhaka', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Dili', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Dubai', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Dushanbe', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Famagusta', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Gaza', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Harbin', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Hebron', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Ho_Chi_Minh', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Hong_Kong', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Hovd', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Irkutsk', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Istanbul', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Jakarta', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Jayapura', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Jerusalem', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Kabul', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Kamchatka', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Karachi', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Kashgar', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Kathmandu', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Katmandu', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Khandyga', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Kolkata', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Krasnoyarsk', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Kuala_Lumpur', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Kuching', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Kuwait', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Macao', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Macau', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Magadan', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Makassar', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Manila', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Muscat', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Nicosia', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Novokuznetsk', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Novosibirsk', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Omsk', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Oral', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Phnom_Penh', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Pontianak', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Pyongyang', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Qatar', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Qostanay', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Qyzylorda', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Rangoon', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Riyadh', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Saigon', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Sakhalin', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Samarkand', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Seoul', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Shanghai', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Singapore', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Srednekolymsk', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Taipei', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Tashkent', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Tbilisi', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Tehran', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Tel_Aviv', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Thimbu', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Thimphu', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Tokyo', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Tomsk', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Ujung_Pandang', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Ulaanbaatar', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Ulan_Bator', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Urumqi', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Ust-Nera', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Vientiane', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Vladivostok', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Yakutsk', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Yangon', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Yekaterinburg', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Asia/Yerevan', N'Asia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Atlantic/Azores', N'Atlantic')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Atlantic/Bermuda', N'Atlantic')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Atlantic/Canary', N'Atlantic')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Atlantic/Cape_Verde', N'Atlantic')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Atlantic/Faeroe', N'Atlantic')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Atlantic/Faroe', N'Atlantic')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Atlantic/Jan_Mayen', N'Atlantic')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Atlantic/Madeira', N'Atlantic')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Atlantic/Reykjavik', N'Atlantic')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Atlantic/South_Georgia', N'Atlantic')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Atlantic/St_Helena', N'Atlantic')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Atlantic/Stanley', N'Atlantic')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/ACT', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Adelaide', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Brisbane', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Broken_Hill', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Canberra', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Currie', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Darwin', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Eucla', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Hobart', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/LHI', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Lindeman', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Lord_Howe', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Melbourne', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/North', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/NSW', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Perth', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Queensland', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/South', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Sydney', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Tasmania', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Victoria', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/West', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Australia/Yancowinna', N'Australia')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Brazil/Acre', N'Brazil')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Brazil/DeNoronha', N'Brazil')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Brazil/East', N'Brazil')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Brazil/West', N'Brazil')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Canada/Atlantic', N'Canada')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Canada/Central', N'Canada')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Canada/Eastern', N'Canada')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Canada/Mountain', N'Canada')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Canada/Newfoundland', N'Canada')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Canada/Pacific', N'Canada')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Canada/Saskatchewan', N'Canada')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Canada/Yukon', N'Canada')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'CET', N'CET')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Chile/Continental', N'Chile')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Chile/EasterIsland', N'Chile')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'CST6CDT', N'CST6CDT')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Cuba', N'Cuba')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'EET', N'EET')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Egypt', N'Egypt')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Eire', N'Eire')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'EST5EDT', N'EST5EDT')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT+0', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT+1', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT+10', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT+11', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT+12', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT+2', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT+3', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT+4', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT+5', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT+6', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT+7', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT+8', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT+9', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT-0', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT-1', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT-10', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT-11', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT-12', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT-13', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT-14', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT-2', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT-3', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT-4', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT-5', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT-6', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT-7', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT-8', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT-9', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/GMT0', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/Greenwich', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/UCT', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/Universal', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/UTC', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Etc/Zulu', N'Etc')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Amsterdam', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Andorra', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Astrakhan', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Athens', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Belfast', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Belgrade', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Berlin', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Bratislava', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Brussels', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Bucharest', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Budapest', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Busingen', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Chisinau', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Copenhagen', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Dublin', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Gibraltar', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Guernsey', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Helsinki', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Isle_of_Man', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Istanbul', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Jersey', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Kaliningrad', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Kiev', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Kirov', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Lisbon', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Ljubljana', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/London', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Luxembourg', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Madrid', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Malta', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Mariehamn', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Minsk', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Monaco', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Moscow', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Nicosia', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Oslo', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Paris', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Podgorica', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Prague', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Riga', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Rome', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Samara', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/San_Marino', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Sarajevo', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Saratov', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Simferopol', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Skopje', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Sofia', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Stockholm', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Tallinn', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Tirane', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Tiraspol', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Ulyanovsk', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Uzhgorod', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Vaduz', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Vatican', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Vienna', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Vilnius', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Volgograd', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Warsaw', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Zagreb', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Zaporozhye', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Europe/Zurich', N'Europe')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'GB', N'GB')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'GB-Eire', N'GB-Eire')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'GMT', N'GMT')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'GMT0', N'GMT0')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Greenwich', N'Greenwich')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Hongkong', N'Hongkong')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Iceland', N'Iceland')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Indian/Antananarivo', N'Indian')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Indian/Chagos', N'Indian')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Indian/Christmas', N'Indian')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Indian/Cocos', N'Indian')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Indian/Comoro', N'Indian')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Indian/Kerguelen', N'Indian')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Indian/Mahe', N'Indian')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Indian/Maldives', N'Indian')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Indian/Mauritius', N'Indian')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Indian/Mayotte', N'Indian')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Indian/Reunion', N'Indian')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Iran', N'Iran')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Israel', N'Israel')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Jamaica', N'Jamaica')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Japan', N'Japan')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Kwajalein', N'Kwajalein')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Libya', N'Libya')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'MET', N'MET')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Mexico/BajaNorte', N'Mexico')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Mexico/BajaSur', N'Mexico')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Mexico/General', N'Mexico')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'MST7MDT', N'MST7MDT')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Navajo', N'Navajo')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'NZ', N'NZ')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'NZ-CHAT', N'NZ-CHAT')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Apia', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Auckland', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Bougainville', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Chatham', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Chuuk', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Easter', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Efate', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Enderbury', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Fakaofo', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Fiji', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Funafuti', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Galapagos', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Gambier', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Guadalcanal', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Guam', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Honolulu', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Johnston', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Kiritimati', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Kosrae', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Kwajalein', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Majuro', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Marquesas', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Midway', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Nauru', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Niue', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Norfolk', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Noumea', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Pago_Pago', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Palau', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Pitcairn', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Pohnpei', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Ponape', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Port_Moresby', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Rarotonga', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Saipan', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Samoa', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Tahiti', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Tarawa', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Tongatapu', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Truk', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Wake', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Wallis', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Pacific/Yap', N'Pacific')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Poland', N'Poland')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Portugal', N'Portugal')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'PRC', N'PRC')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'PST8PDT', N'PST8PDT')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'ROK', N'ROK')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Singapore', N'Singapore')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'SystemV/AST4', N'SystemV')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'SystemV/AST4ADT', N'SystemV')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'SystemV/CST6', N'SystemV')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'SystemV/CST6CDT', N'SystemV')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'SystemV/EST5', N'SystemV')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'SystemV/EST5EDT', N'SystemV')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'SystemV/HST10', N'SystemV')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'SystemV/MST7', N'SystemV')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'SystemV/MST7MDT', N'SystemV')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'SystemV/PST8', N'SystemV')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'SystemV/PST8PDT', N'SystemV')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'SystemV/YST9', N'SystemV')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'SystemV/YST9YDT', N'SystemV')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Turkey', N'Turkey')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'UCT', N'UCT')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Universal', N'Universal')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'US/Alaska', N'US')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'US/Aleutian', N'US')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'US/Arizona', N'US')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'US/Central', N'US')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'US/East-Indiana', N'US')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'US/Eastern', N'US')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'US/Hawaii', N'US')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'US/Indiana-Starke', N'US')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'US/Michigan', N'US')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'US/Mountain', N'US')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'US/Pacific', N'US')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'US/Pacific-New', N'US')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'US/Samoa', N'US')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'UTC', N'UTC')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'W-SU', N'W-SU')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'WET', N'WET')
	INSERT [dbo].[time_zones] ([time_zone], [short_zone]) VALUES (N'Zulu', N'Zulu')
END